
Style/FrozenStringLiteralComment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - db/seeds.rb
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - spec/**/*.rb
    - config/environments/production.rb
Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

AllCops:
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - app/channels/.rb
